# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               eDC
tagline:             'explore > develop > conquer'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://edcamity.com/blogdev
baseurl:             'http://edcamity.com/blogdev'
paginate:            5

# About/contact
author:
	suvil:
  		name:              Suvil Sipani
  		url:               http://suvilsipani.com
  		email:             suvil@suvilsipani.com
  	ishani:
  		name:			   Ishani Luthra
  		url: 			   ishaniluthra@gmail.com

# Custom vars
version:             1.0.0
